# These are supported funding model platforms

github: [halotroop2288, Amb0s, SuperCoder7979, valoeghese]
patreon: halotroop2288
open_collective: # Replace with a single Open Collective username
ko_fi: halotroop2288
custom: ['paypal.me/halotroop2288']
