name: Build Mod and Upload Artifact
on: [push]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
        with:
          lfs: true

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Allow Access
        if:  contains(${{ matrix.os}}, ubuntu)
        run: chmod +x gradlew

      - name: Build Mod JARs
        run: ./gradlew build --refresh-dependencies

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: JARs
          path: build/libs
