name: Build Mod
on: [pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        java-version: [8, 11, 13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
        with:
          lfs: true

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Allow Access
        run: chmod +x gradlew

      - name: Build Mod
        run: ./gradlew build --refresh-dependencies
