name: Test PR/Workflow Integrity
on:
  pull_request:
    paths: [ '**.java', '**.gradle', 'gradle.properties' ]
  push:
    paths: [ '.github/workflows/', '.github/workflows/on_push.yml' ]
jobs:
  gradle:
    strategy:
      matrix:
        minecraftVersion: [1.15, 1.15.1, 1.15.2]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Allow Permissions
        run: chmod +x ./gradlew
      - name: "Run Fabric Tests"
        uses: Geometrically/fabric-test-runner@v1.1
        id: testRunner
        with:
          minecraftVersion: ${{ matrix.minecraftVersion }}
