name: Build Mod and Upload Artifact
on: 
  push:
    paths: [ '**.java', '**.gradle', 'gradle.properties' ]
jobs:
  gradle:
    strategy:
      matrix:
        minecraftVersion: [ 1.15, 1.15.1, 1.15.2 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          with:
            lfs: true
        - name: "Allow Permissions"
          run: chmod +x ./gradlew
        - name: "Run Fabric Tests"
          uses: Geometrically/fabric-test-runner@v1
          id: testRunner
          with:
            minecraftVersion: ${{ matrix.minecraftVersion }}
        - name: "Upload Artifacts"
          uses: actions/upload-artifact@v1.1
          with:
            name: Builds
            path: build/libs
