name: Test PR Integrity
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        java-version: [8, 11, 13]
        minecraftVersion: [1.15, 1.15.1, 1.15.2]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: "Run Fabric Tests"
        uses: Geometrically/fabric-test-runner@v1
        id: testRunner
        with:
          minecraftVersion: ${{ matrix.minecraftVersion }}
